### ISSUE TITLE
Setup AuthN and AuthZ 

### ISSUE THREAD

**Issue by ChethanUK** [apache/airflow-on-k8s-operator#7]
Not able to find resources on AuthN and AuthZ

How can I use something like IAM or [dex](https://github.com/dexidp/dex)?

**Comment by mik-laj** [comment]
It's part of the Airflow configuration. Here is more information: https://airflow.readthedocs.io/en/latest/security.html. You could also use [IAP](https://cloud.google.com/iap/) but this forces the user mechanism in Airflow to be turned off. All users will be admin.
