### ISSUE TITLE
Setup CI for the repo

### ISSUE THREAD

**Issue by barney-s** [apache/airflow-on-k8s-operator#8]
Use travis or equivalent to setup CI for qualified pull requests.

**Comment by feng-tao** [comment]
cc @kaxil , is it something we need to ask apache infra to help ?

**Comment by kaxil** [comment]
> cc @kaxil , is it something we need to ask apache infra to help ?

Yes we do, will raise an issue now

**Comment by kaxil** [comment]
Created one at https://issues.apache.org/jira/browse/INFRA-19903

**Comment by kaxil** [comment]
Travis is enabled. Test: https://travis-ci.org/apache/airflow-on-k8s-operator/builds/656638605
Test PR: https://github.com/apache/airflow-on-k8s-operator/pull/9

**Comment by kaxil** [comment]
Just create `travis.yml` and add configs :)
